# Users

## Создать нового пользователя

POST http://localhost:5000/users/register HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="avatar-angelina.jpg"
Content-Type: image/jpeg

< /Users/User/Pictures/avatar-angelina.jpg

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="user"
Content-Type: application/json

{
  "email": "torans@overlook.net",
  "avatar": "torrance.png",
  "name": "Jack",
  "password": "shining",
  "type": "pro"
}

###

## Авторизовать пользователя

POST http://localhost:5000/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "torans@overlook.net",
  "password": "shining"
}

###

## Отправка аватарки пользователю
#Home
POST http://localhost:5000/users/647ae1b0185a102c71b0d93a/avatar HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRvcmFuc0BvdmVybG9vay5uZXQiLCJpZCI6IjY0ODU2OTNlNThkM2FmODI1YWRhYTE1MyIsImlhdCI6MTY4NjQ3OTE1NywiZXhwIjoxNjg2NjUxOTU3LCJqdGkiOiI4ZDQwYWU5Zi1kNGJjLTRjYTQtYjZmNS05MDlhMzg2ZWEyODYifQ.TOsU09nVoWkdgOgEBQsDMW1ELnQ_QX-Vupt93Eq0NnI

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="avatar-angelina.jpg"
Content-Type: image/png

< /Users/User/Pictures/avatar-angelina.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW

###
## Отправка аватарки пользователю
#Work
POST http://localhost:5000/users/646df98fc7c8538bbd749e9e/avatar HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRvcmFuc0BvdmVybG9vay5uZXQiLCJpZCI6IjY0ODU2OTNlNThkM2FmODI1YWRhYTE1MyIsImlhdCI6MTY4NjQ3OTE1NywiZXhwIjoxNjg2NjUxOTU3LCJqdGkiOiI4ZDQwYWU5Zi1kNGJjLTRjYTQtYjZmNS05MDlhMzg2ZWEyODYifQ.TOsU09nVoWkdgOgEBQsDMW1ELnQ_QX-Vupt93Eq0NnI

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="avatar-angelina.jpg"
Content-Type: image/jpeg

< /home/oem/Pictures/avatar-angelina.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW

###

## Проверить токен пользователя
GET http://localhost:5000/users/login HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRvcmFuc0BvdmVybG9vay5uZXQiLCJpZCI6IjY0ODU2OTNlNThkM2FmODI1YWRhYTE1MyIsImlhdCI6MTY4NjQ3OTE1NywiZXhwIjoxNjg2NjUxOTU3LCJqdGkiOiI4ZDQwYWU5Zi1kNGJjLTRjYTQtYjZmNS05MDlhMzg2ZWEyODYifQ.TOsU09nVoWkdgOgEBQsDMW1ELnQ_QX-Vupt93Eq0NnI

###

## Выйти из закрытой части приложения
POST http://localhost:5000/users/logout HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRvcmFuc0BvdmVybG9vay5uZXQiLCJpZCI6IjY0ODU2OTNlNThkM2FmODI1YWRhYTE1MyIsImlhdCI6MTY4NjQ2NDkyMSwiZXhwIjoxNjg2NjM3NzIxLCJqdGkiOiI4NzQ1ZGQ4My1jYWU5LTQwZWQtODI0YS02NzZlMDkyZWFlYjAifQ.gLEzZycNptFoWBKfCIDYh7nptpmiOpO5HXlc4EJTMVc

###
