#Favorites
## Добавить в избранное
POST http://localhost:5000/favorites/64872a65f6f1f8fa4dc16bc8 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRvcmFuc0BvdmVybG9vay5uZXQiLCJpZCI6IjY0ODU2OTNlNThkM2FmODI1YWRhYTE1MyIsImlhdCI6MTY4NjgzMjg1OSwiZXhwIjoxNjg3MDA1NjU5LCJqdGkiOiI3ZDgxYTljYy01NTIwLTQ3MzAtODZiNC03YzJkMGY5OGMxNWUifQ.WhoYSCabk05jpxndWFWci9Zu4jqbNad6RXdvJeas638

{
  "isFavorite": "true"
}
###
