#Favorites
## Добавить в избранное
POST http://localhost:5000/favorites/64872a65f6f1f8fa4dc16bc8 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRvcmFuc0BvdmVybG9vay5uZXQiLCJpZCI6IjY0ODU2OTNlNThkM2FmODI1YWRhYTE1MyIsImlhdCI6MTY4NjQ3OTE1NywiZXhwIjoxNjg2NjUxOTU3LCJqdGkiOiI4ZDQwYWU5Zi1kNGJjLTRjYTQtYjZmNS05MDlhMzg2ZWEyODYifQ.TOsU09nVoWkdgOgEBQsDMW1ELnQ_QX-Vupt93Eq0NnI

{
  "isFavorite": "true"
}
###
